export const USER_REPOSITORY = 'USER_REPOSITORY';
export const TIME_REPOSITORY = 'TIME_REPOSITORY';
export const TOKEN_REPOSITORY = 'TOKEN_REPOSITORY';
export const REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY';
